version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: swapper071983/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db

  frontend:
    image: swapper071983/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    image: swapper071983/foodgram_nginx 
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/static/
      - media:/media/
    ports:
      - 8750:80
    depends_on:
      - frontend
      - backend