version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: swapper071983/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: swapper071983/foodgram_frontend 
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
      
  gateway:
    image: swapper071983/foodgram_gateway  
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 8750:80
    depends_on:
      - backend
      - frontend